// Parses the NRC raw.txt and outputs js/nrcLexicon.js — a static JS module
// mapping each word to archetype scores derived from NRC emotion weights.
// Run once with: node scripts/buildLexicon.js

const fs = require('fs');
const path = require('path');

// How much each NRC emotion contributes to each cinematic archetype.
// Epic requires anger to avoid firing on generic positive/anticipation words.
// Romantic uses joy+trust but NOT anger to stay distinct from epic.
const EMOTION_WEIGHTS = {
  tense:       { fear: 3, anger: 2, negative: 1 },
  romantic:    { joy: 3, trust: 3, positive: 1 },
  epic:        { anger: 3, anticipation: 2, trust: 1 },
  mysterious:  { fear: 2, surprise: 3, disgust: 1, negative: 1 },
  peaceful:    { joy: 2, trust: 2, positive: 3 },
  melancholic: { sadness: 3, negative: 2, disgust: 1 },
};

const ARCHETYPES = Object.keys(EMOTION_WEIGHTS);

const rawPath = path.join(__dirname, '../node_modules/nrc-emotion-words/raw.txt');
const lines = fs.readFileSync(rawPath, 'utf8').trim().split('\n');

// Build word → { emotion: score } map from raw data
const wordEmotions = {};
for (const line of lines) {
  const [word, emotion, score] = line.split('\t');
  if (score === '1') {
    if (!wordEmotions[word]) wordEmotions[word] = {};
    wordEmotions[word][emotion] = 1;
  }
}

// Convert to archetype scores
const lexicon = {};
for (const [word, emotions] of Object.entries(wordEmotions)) {
  const archetypeScores = {};
  let hasAny = false;

  for (const archetype of ARCHETYPES) {
    let score = 0;
    for (const [emotion, weight] of Object.entries(EMOTION_WEIGHTS[archetype])) {
      if (emotions[emotion]) score += weight;
    }
    if (score > 0) {
      archetypeScores[archetype] = Math.round(score * 10) / 10;
      hasAny = true;
    }
  }

  if (hasAny) lexicon[word] = archetypeScores;
}

const wordCount = Object.keys(lexicon).length;
console.log(`Generated ${wordCount} words with archetype scores.`);

// Emit as an ES module
const outPath = path.join(__dirname, '../js/nrcLexicon.js');
const output = `// Auto-generated by scripts/buildLexicon.js — do not edit manually.
// ${wordCount} words derived from the NRC Word-Emotion Association Lexicon.
// Saif Mohammad & Peter Turney, NRC, 2010.
export const lexicon = ${JSON.stringify(lexicon)};
`;

fs.writeFileSync(outPath, output);
console.log(`Written to js/nrcLexicon.js`);
